In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [18]:
df = pd.read_csv("/Users/zaynsmacantosh/Downloads/fake.csv")  # Replace with your dataset file path
print(df.head())


                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  


In [4]:
df = df.dropna() 
# Step 3: Preprocessing
# Drop any rows with missing values

In [21]:
# Separate labels and features
X = df['text']  # Text of the article
y = df['subject']  # Label: 'REAL' or 'FAKE'



In [7]:
# Display the column names in the dataset
print(df.columns)



Index(['title', 'text', 'subject', 'date'], dtype='object')


In [8]:
# Display the first few rows of the dataset
print(df.head())




                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  


In [9]:
# Separate labels and features
X = df['text']  # Text of the article
y = df['subject']  # Replace with the column that has "FAKE" or "REAL" labels


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)


In [11]:
# Step 5: Text vectorization
# Using TfidfVectorizer to convert text to numerical features
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

In [12]:
# Step 6: Model Training
# Use PassiveAggressiveClassifier (a good baseline for text classification tasks)
model = PassiveAggressiveClassifier(max_iter=50)
model.fit(tfidf_train, y_train)

PassiveAggressiveClassifier(max_iter=50)

In [13]:
# Step 7: Model Evaluation
# Predict and calculate accuracy
y_pred = model.predict(tfidf_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 51.14%


In [14]:
# Confusion Matrix
confusion = confusion_matrix(y_test, y_pred, labels=['FAKE', 'REAL'])
print("Confusion Matrix:")
print(confusion)

ValueError: At least one label specified must be in y_true

In [22]:
print(y_test.unique())


['News' 'left-news' 'politics' 'Middle-east' 'Government News' 'US_News']


In [23]:
# Use your unique labels from y_test in the confusion matrix
unique_labels = ['News', 'left-news', 'politics', 'Middle-east', 'Government News', 'US_News']
confusion = confusion_matrix(y_test, y_pred, labels=unique_labels)  # Set these labels

print("Confusion Matrix:")
print(confusion)

Confusion Matrix:
[[1704    7   11    0    1    0]
 [  18  137  679    0   58    0]
 [  41  706  492    3  167    0]
 [   1    0    0   11    0  160]
 [   9   92  201    1   32    0]
 [   2    0    0  138    0   26]]


In [24]:
# Step 8: Testing the model with a custom input
def predict_news(text):
    transformed_text = tfidf_vectorizer.transform([text])
    prediction = model.predict(transformed_text)
    return prediction[0]

In [25]:
# Example test
print(predict_news("Type your test news article here."))

left-news


In [27]:
# Example test
print(predict_news("Pope Francis Just Called Out Donald Trump Dur..."))

News
